excel:
  file: cases.xlsx

logger:
  name: "Gritli"
  file: "log.txt"
  logger_level: "DEBUG"
  stream_level: "DEBUG"
  file_level: "INFO"


user:
  username: "liyijj"
  password: "123456"

selenium:
  wait_time: 20

host: "http://120.78.128.25:8765/"









